#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${ROOT_DIR}/scripts/_common.sh"

PYTHON_BIN="${ROOT_DIR}/fprime-venv/bin/python"
TARGET_BASELINE_MANAGER="${ROOT_DIR}/scripts/comm_verification/lib/ensure_target_comm_lab_baseline.py"
SURFACE_OWNER="${ROOT_DIR}/scripts/manual_ops/lib/surface_owner.py"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  echo "python interpreter not found at ${PYTHON_BIN}. Build/setup the repo first." >&2
  exit 1
fi

JSON_OUT="${JSON_OUT:-${TARGET_BASELINE_JSON_OUT:-}}"

OBC_SSH_TARGET="${OBC_SSH_TARGET:-$(obc_resolve_obc_ssh_target)}"
SUBSYSTEM_SIM_SSH_TARGET="${SUBSYSTEM_SIM_SSH_TARGET:-$(obc_resolve_subsystem_sim_ssh_target)}"
OBC_CAN_SERVICE_NAME="${OBC_CAN_SERVICE_NAME:-obc-lab-can.service}"
SUBSYSTEM_EPS_ADCS_CAN_SERVICE_NAME="${SUBSYSTEM_EPS_ADCS_CAN_SERVICE_NAME:-subsystem-eps-adcs-lab-can.service}"
SUBSYSTEM_COMM_CAN_SERVICE_NAME="${SUBSYSTEM_COMM_CAN_SERVICE_NAME:-subsystem-comm-lab-can.service}"
OBC_COMM_CSP_SERVICE_NAME="${OBC_COMM_CSP_SERVICE_NAME:-obc-comm-csp-stack.service}"
EPS_SERVICE_NAME="${EPS_SERVICE_NAME:-subsystem-eps-csp.service}"
ADCS_SERVICE_NAME="${ADCS_SERVICE_NAME:-subsystem-adcs-csp.service}"
SBAND_STACK_TARGET_NAME="${SBAND_STACK_TARGET_NAME:-subsystem-sband-csp-stack.target}"
UHF_STACK_TARGET_NAME="${UHF_STACK_TARGET_NAME:-subsystem-uhf-csp-stack.target}"
SBAND_COMM_SERVICE_NAME="${SBAND_COMM_SERVICE_NAME:-subsystem-sband-csp.service}"
UHF_COMM_SERVICE_NAME="${UHF_COMM_SERVICE_NAME:-subsystem-uhf-csp.service}"
OBC_CSP_CAN_DEVICE="${OBC_CSP_CAN_DEVICE:-can0}"
SUBSYSTEM_SIM_CSP_CAN_DEVICE="${SUBSYSTEM_SIM_CSP_CAN_DEVICE:-can0}"
SUBSYSTEM_SIM_COMM_CAN_DEVICE="${SUBSYSTEM_SIM_COMM_CAN_DEVICE:-can1}"
TARGET_BASELINE_COMM_CSP_SOCKETCAN_USE_CANFD="${TARGET_BASELINE_COMM_CSP_SOCKETCAN_USE_CANFD:-1}"
TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DEST_ALLOWLIST="${TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DEST_ALLOWLIST:-5,6}"
TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DPORT_ALLOWLIST="${TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DPORT_ALLOWLIST:-40}"
SBAND_TCP_PORT="${SBAND_TCP_PORT:-18520}"

env_args=(
  OBC_SSH_TARGET="${OBC_SSH_TARGET}"
  SUBSYSTEM_SIM_SSH_TARGET="${SUBSYSTEM_SIM_SSH_TARGET}"
  OBC_CAN_SERVICE_NAME="${OBC_CAN_SERVICE_NAME}"
  SUBSYSTEM_EPS_ADCS_CAN_SERVICE_NAME="${SUBSYSTEM_EPS_ADCS_CAN_SERVICE_NAME}"
  SUBSYSTEM_COMM_CAN_SERVICE_NAME="${SUBSYSTEM_COMM_CAN_SERVICE_NAME}"
  OBC_COMM_CSP_SERVICE_NAME="${OBC_COMM_CSP_SERVICE_NAME}"
  EPS_SERVICE_NAME="${EPS_SERVICE_NAME}"
  ADCS_SERVICE_NAME="${ADCS_SERVICE_NAME}"
  SBAND_STACK_TARGET_NAME="${SBAND_STACK_TARGET_NAME}"
  UHF_STACK_TARGET_NAME="${UHF_STACK_TARGET_NAME}"
  SBAND_COMM_SERVICE_NAME="${SBAND_COMM_SERVICE_NAME}"
  UHF_COMM_SERVICE_NAME="${UHF_COMM_SERVICE_NAME}"
  OBC_CSP_CAN_DEVICE="${OBC_CSP_CAN_DEVICE}"
  SUBSYSTEM_SIM_CSP_CAN_DEVICE="${SUBSYSTEM_SIM_CSP_CAN_DEVICE}"
  SUBSYSTEM_SIM_COMM_CAN_DEVICE="${SUBSYSTEM_SIM_COMM_CAN_DEVICE}"
  TARGET_BASELINE_COMM_CSP_SOCKETCAN_USE_CANFD="${TARGET_BASELINE_COMM_CSP_SOCKETCAN_USE_CANFD}"
  TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DEST_ALLOWLIST="${TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DEST_ALLOWLIST}"
  TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DPORT_ALLOWLIST="${TARGET_BASELINE_COMM_CSP_SOCKETCAN_CANFD_DPORT_ALLOWLIST}"
  SBAND_TCP_PORT="${SBAND_TCP_PORT}"
)

if [[ -n "${JSON_OUT}" ]]; then
  env "${env_args[@]}" "${PYTHON_BIN}" "${TARGET_BASELINE_MANAGER}" --json-out "${JSON_OUT}"
else
  env "${env_args[@]}" "${PYTHON_BIN}" "${TARGET_BASELINE_MANAGER}"
fi

if [[ "${TARGET_BASELINE_INCLUDE_MANUAL_AUTH_PREFLIGHT:-0}" == "1" ]]; then
  env "${env_args[@]}" "${PYTHON_BIN}" "${SURFACE_OWNER}" target-manual-auth-preflight-apply
fi
