#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${ROOT_DIR}/scripts/_common.sh"

SUBSYSTEM_SIM_SSH_TARGET="${SUBSYSTEM_SIM_SSH_TARGET:-$(obc_resolve_subsystem_sim_ssh_target)}"
SUBSYSTEM_SIM_REMOTE_DIR="${SUBSYSTEM_SIM_REMOTE_DIR:-$(obc_resolve_subsystem_sim_remote_dir)}"
CSP_TRANSPORT="${CSP_TRANSPORT:-socketcan}"
SUBSYSTEM_SIM_CSP_CAN_DEVICE="${SUBSYSTEM_SIM_CSP_CAN_DEVICE:-}"
SUBSYSTEM_SIM_COMM_CAN_DEVICE="${SUBSYSTEM_SIM_COMM_CAN_DEVICE:-}"
SUBSYSTEM_SIM_COMM_DEVICE="${SUBSYSTEM_SIM_COMM_DEVICE:-${COMM_DEVICE:-/dev/serial0}}"
COMM_BAUDRATE="${COMM_BAUDRATE:-115200}"
CSP_CAN_PROMISC="${CSP_CAN_PROMISC:-0}"
EPS_CSP_NODE_ID="${EPS_CSP_NODE_ID:-2}"
ADCS_CSP_NODE_ID="${ADCS_CSP_NODE_ID:-3}"
COMM_CSP_NODE="${COMM_CSP_NODE:-4}"
KILL_EXISTING_PIDS="${KILL_EXISTING_PIDS:-1}"

REMOTE_CMD="set -euo pipefail"
REMOTE_CMD+=" && cd $(printf '%q' "${SUBSYSTEM_SIM_REMOTE_DIR}")"
REMOTE_CMD+=" && bash scripts/run_subsystem_sim_comm_can_stack.sh"

obc_ssh "${SUBSYSTEM_SIM_SSH_TARGET}" \
  env \
  CSP_TRANSPORT="${CSP_TRANSPORT}" \
  SUBSYSTEM_SIM_CSP_CAN_DEVICE="${SUBSYSTEM_SIM_CSP_CAN_DEVICE}" \
  SUBSYSTEM_SIM_COMM_CAN_DEVICE="${SUBSYSTEM_SIM_COMM_CAN_DEVICE}" \
  SUBSYSTEM_SIM_COMM_DEVICE="${SUBSYSTEM_SIM_COMM_DEVICE}" \
  COMM_BAUDRATE="${COMM_BAUDRATE}" \
  CSP_CAN_PROMISC="${CSP_CAN_PROMISC}" \
  EPS_CSP_NODE_ID="${EPS_CSP_NODE_ID}" \
  ADCS_CSP_NODE_ID="${ADCS_CSP_NODE_ID}" \
  COMM_CSP_NODE="${COMM_CSP_NODE}" \
  KILL_EXISTING_PIDS="${KILL_EXISTING_PIDS}" \
  /bin/bash -lc "$(printf '%q' "${REMOTE_CMD}")"
