#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${ROOT_DIR}/scripts/_common.sh"

PYTHON_BIN="${ROOT_DIR}/fprime-venv/bin/python"
WATCHDOG_PROBE_PY="${ROOT_DIR}/scripts/comm_verification/lib/run_rpi_target_hardware_watchdog_reset_probe.py"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  echo "python interpreter not found at ${PYTHON_BIN}. Build/setup the repo first." >&2
  exit 1
fi

OBC_SSH_TARGET="${OBC_SSH_TARGET:-$(obc_resolve_obc_ssh_target)}"
SUBSYSTEM_SIM_SSH_TARGET="${SUBSYSTEM_SIM_SSH_TARGET:-$(obc_resolve_subsystem_sim_ssh_target)}"
RUNTIME_ROOT="${RUNTIME_ROOT:-}"
OBC_COMM_CSP_SERVICE_NAME="${OBC_COMM_CSP_SERVICE_NAME:-obc-comm-csp-stack.service}"
REBOOT_TIMEOUT_SEC="${REBOOT_TIMEOUT_SEC:-180}"
SERVICE_ACTIVE_TIMEOUT_SEC="${SERVICE_ACTIVE_TIMEOUT_SEC:-120}"
SSH_DOWN_TIMEOUT_SEC="${SSH_DOWN_TIMEOUT_SEC:-60}"
VERIFY_COMMAND_PATH="${VERIFY_COMMAND_PATH:-1}"
HOST_SERIAL_DEVICE="${HOST_SERIAL_DEVICE:-/dev/cu.usbserial-CHANGE_ME}"
COMM_BAUDRATE="${COMM_BAUDRATE:-115200}"
TARGET_COMM_PROFILE="${TARGET_COMM_PROFILE:-sband}"
SBAND_TCP_HOST="${SBAND_TCP_HOST:-$(obc_resolve_subsystem_sim_host)}"
SBAND_TCP_PORT="${SBAND_TCP_PORT:-18520}"
TARGET_BASELINE_REQUIRE_UHF_SERVICE="${TARGET_BASELINE_REQUIRE_UHF_SERVICE:-1}"
WATCHDOG_SOURCE="${WATCHDOG_SOURCE:-adcs-fdir}"
PROFILE_OVERRIDE_DROPIN_NAME="${PROFILE_OVERRIDE_DROPIN_NAME:-51-target-comm-profile-override.conf}"
PROBE_TMP_DIR="${PROBE_TMP_DIR:-$(mktemp -d "/tmp/rpi-hw-watchdog-reset.XXXXXX")}"

SBAND_STACK_TARGET_NAME="${SBAND_STACK_TARGET_NAME:-$(obc_target_comm_profile_subsystem_stack_target sband)}"
UHF_STACK_TARGET_NAME="${UHF_STACK_TARGET_NAME:-$(obc_target_comm_profile_subsystem_stack_target uhf-primary)}"
SBAND_COMM_SERVICE_NAME="${SBAND_COMM_SERVICE_NAME:-$(obc_target_comm_profile_subsystem_comm_service sband)}"
UHF_COMM_SERVICE_NAME="${UHF_COMM_SERVICE_NAME:-$(obc_target_comm_profile_subsystem_comm_service uhf-primary)}"
EPS_SERVICE_NAME="${EPS_SERVICE_NAME:-subsystem-eps-csp.service}"
ADCS_SERVICE_NAME="${ADCS_SERVICE_NAME:-subsystem-adcs-csp.service}"
TARGET_SERVICE_PROFILE="${TARGET_SERVICE_PROFILE:-sband}"
TARGET_SERVICE_COMMAND_AUTHORITY_PROFILE="${TARGET_SERVICE_COMMAND_AUTHORITY_PROFILE:-sband-primary}"
TARGET_SERVICE_INITIAL_COMM_BAND="${TARGET_SERVICE_INITIAL_COMM_BAND:-sband}"
TARGET_SERVICE_ENABLE_PRIMARY_GROUND_LINK_DRIVER="${TARGET_SERVICE_ENABLE_PRIMARY_GROUND_LINK_DRIVER:-1}"
TARGET_COMMAND_AUTHORITY_PROFILE="${TARGET_COMMAND_AUTHORITY_PROFILE:-sband-primary}"
TARGET_COMM_CSP_NODE="${TARGET_COMM_CSP_NODE:-5}"
TARGET_REQUIRES_UHF_PRIMARY_SWITCH="${TARGET_REQUIRES_UHF_PRIMARY_SWITCH:-0}"
RPI_INSTALL_ROOT="${RPI_INSTALL_ROOT:-/home/operator/obc-deploy}"
OBC_GROUNDLINK_DIAGNOSTICS="${OBC_GROUNDLINK_DIAGNOSTICS:-1}"
UHF_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME="${UHF_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME:-54-uhf-ingress-diagnostics.conf}"
UHF_COMM_NODE_INGRESS_DIAGNOSTICS="${UHF_COMM_NODE_INGRESS_DIAGNOSTICS:-0}"
SBAND_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME="${SBAND_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME:-58-sband-ingress-diagnostics.conf}"
SBAND_COMM_NODE_INGRESS_DIAGNOSTICS="${SBAND_COMM_NODE_INGRESS_DIAGNOSTICS:-1}"

obc_require_systemd_service_name "${OBC_COMM_CSP_SERVICE_NAME}"
obc_require_target_comm_profile "${TARGET_COMM_PROFILE}"
obc_require_systemd_service_name "${SBAND_COMM_SERVICE_NAME}"
obc_require_systemd_service_name "${UHF_COMM_SERVICE_NAME}"
obc_require_systemd_service_name "${EPS_SERVICE_NAME}"
obc_require_systemd_service_name "${ADCS_SERVICE_NAME}"
if [[ ! "${SBAND_STACK_TARGET_NAME}" =~ ^[A-Za-z0-9_.@:-]+\.target$ || \
  ! "${UHF_STACK_TARGET_NAME}" =~ ^[A-Za-z0-9_.@:-]+\.target$ ]]; then
  echo "SBAND_STACK_TARGET_NAME and UHF_STACK_TARGET_NAME must be safe systemd target names ending in .target." >&2
  exit 1
fi
if [[ "${VERIFY_COMMAND_PATH}" != "1" ]]; then
  echo "target hardware watchdog reset probe requires VERIFY_COMMAND_PATH=1." >&2
  exit 1
fi

mkdir -p "${PROBE_TMP_DIR}"

exec env \
  OBC_SSH_TARGET="${OBC_SSH_TARGET}" \
  SUBSYSTEM_SIM_SSH_TARGET="${SUBSYSTEM_SIM_SSH_TARGET}" \
  ROOT_DIR="${ROOT_DIR}" \
  RUNTIME_ROOT="${RUNTIME_ROOT}" \
  OBC_COMM_CSP_SERVICE_NAME="${OBC_COMM_CSP_SERVICE_NAME}" \
  EPS_SERVICE_NAME="${EPS_SERVICE_NAME}" \
  ADCS_SERVICE_NAME="${ADCS_SERVICE_NAME}" \
  SBAND_STACK_TARGET_NAME="${SBAND_STACK_TARGET_NAME}" \
  UHF_STACK_TARGET_NAME="${UHF_STACK_TARGET_NAME}" \
  SBAND_COMM_SERVICE_NAME="${SBAND_COMM_SERVICE_NAME}" \
  UHF_COMM_SERVICE_NAME="${UHF_COMM_SERVICE_NAME}" \
  REBOOT_TIMEOUT_SEC="${REBOOT_TIMEOUT_SEC}" \
  SERVICE_ACTIVE_TIMEOUT_SEC="${SERVICE_ACTIVE_TIMEOUT_SEC}" \
  SSH_DOWN_TIMEOUT_SEC="${SSH_DOWN_TIMEOUT_SEC}" \
  RESTART_TIMEOUT_SEC="${SERVICE_ACTIVE_TIMEOUT_SEC}" \
  ADCS_RESTORE_TIMEOUT_SEC="${SERVICE_ACTIVE_TIMEOUT_SEC}" \
  VERIFY_COMMAND_PATH="${VERIFY_COMMAND_PATH}" \
  HOST_SERIAL_DEVICE="${HOST_SERIAL_DEVICE}" \
  COMM_BAUDRATE="${COMM_BAUDRATE}" \
  TARGET_COMM_PROFILE="${TARGET_COMM_PROFILE}" \
  TARGET_SERVICE_PROFILE="${TARGET_SERVICE_PROFILE}" \
  TARGET_SERVICE_COMMAND_AUTHORITY_PROFILE="${TARGET_SERVICE_COMMAND_AUTHORITY_PROFILE}" \
  TARGET_SERVICE_INITIAL_COMM_BAND="${TARGET_SERVICE_INITIAL_COMM_BAND}" \
  TARGET_SERVICE_ENABLE_PRIMARY_GROUND_LINK_DRIVER="${TARGET_SERVICE_ENABLE_PRIMARY_GROUND_LINK_DRIVER}" \
  TARGET_COMMAND_AUTHORITY_PROFILE="${TARGET_COMMAND_AUTHORITY_PROFILE}" \
  TARGET_COMM_CSP_NODE="${TARGET_COMM_CSP_NODE}" \
  TARGET_REQUIRES_UHF_PRIMARY_SWITCH="${TARGET_REQUIRES_UHF_PRIMARY_SWITCH}" \
  TARGET_BASELINE_REQUIRE_UHF_SERVICE="${TARGET_BASELINE_REQUIRE_UHF_SERVICE}" \
  SBAND_TCP_HOST="${SBAND_TCP_HOST}" \
  SBAND_TCP_PORT="${SBAND_TCP_PORT}" \
  WATCHDOG_SOURCE="${WATCHDOG_SOURCE}" \
  PROFILE_OVERRIDE_DROPIN_NAME="${PROFILE_OVERRIDE_DROPIN_NAME}" \
  RPI_INSTALL_ROOT="${RPI_INSTALL_ROOT}" \
  OBC_GROUNDLINK_DIAGNOSTICS="${OBC_GROUNDLINK_DIAGNOSTICS}" \
  UHF_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME="${UHF_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME}" \
  UHF_COMM_NODE_INGRESS_DIAGNOSTICS="${UHF_COMM_NODE_INGRESS_DIAGNOSTICS}" \
  SBAND_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME="${SBAND_INGRESS_DIAGNOSTICS_OVERRIDE_DROPIN_NAME}" \
  SBAND_COMM_NODE_INGRESS_DIAGNOSTICS="${SBAND_COMM_NODE_INGRESS_DIAGNOSTICS}" \
  TARGET_BASELINE_MANAGED_EXTERNALLY="1" \
  PROBE_TMP_DIR="${PROBE_TMP_DIR}" \
  "${PYTHON_BIN}" "${WATCHDOG_PROBE_PY}"
