#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${ROOT_DIR}/scripts/_common.sh"

OBC_SSH_TARGET="${OBC_SSH_TARGET:-$(obc_resolve_obc_ssh_target)}"
RPI_INSTALL_ROOT="${RPI_INSTALL_ROOT:-/home/operator/obc-deploy}"
GDS_HOST="${GDS_HOST:-$(obc_default_gds_host)}"
GDS_PORT="${GDS_PORT:-0}"
RADIO_PORT="${RADIO_PORT:-7000}"
OBC_BINARY_NAME="${OBC_BINARY_NAME:-OBC}"
GROUND_LINK_MODE="${GROUND_LINK_MODE:-direct-tcp}"
COMM_CSP_NODE="${COMM_CSP_NODE:-4}"
CSP_TRANSPORT="${CSP_TRANSPORT:-zmqhub}"
RUNTIME_ROOT="${RUNTIME_ROOT:-${RPI_INSTALL_ROOT}/runtime/integ-rpi}"
PERSISTENT_ROOT="${PERSISTENT_ROOT:-${RUNTIME_ROOT}/persistent-data}"
STAGING_ROOT="${STAGING_ROOT:-${RUNTIME_ROOT}/staging}"
LOG_ROOT="${LOG_ROOT:-${RUNTIME_ROOT}/logs}"
REMOTE_RELEASE_ROOT="${RPI_INSTALL_ROOT}/current"

REMOTE_CMD="set -euo pipefail"
REMOTE_CMD+=" && test -x $(printf '%q' "${REMOTE_RELEASE_ROOT}/launch/run_stack.sh")"
REMOTE_CMD+=" && mkdir -p $(printf '%q' "${PERSISTENT_ROOT}") $(printf '%q' "${STAGING_ROOT}") $(printf '%q' "${LOG_ROOT}")"
REMOTE_CMD+=" && export GDS_HOST=$(printf '%q' "${GDS_HOST}")"
REMOTE_CMD+=" && export GDS_PORT=$(printf '%q' "${GDS_PORT}")"
REMOTE_CMD+=" && export RADIO_PORT=$(printf '%q' "${RADIO_PORT}")"
REMOTE_CMD+=" && export OBC_BINARY_NAME=$(printf '%q' "${OBC_BINARY_NAME}")"
REMOTE_CMD+=" && export GROUND_LINK_MODE=$(printf '%q' "${GROUND_LINK_MODE}")"
REMOTE_CMD+=" && export COMM_CSP_NODE=$(printf '%q' "${COMM_CSP_NODE}")"
REMOTE_CMD+=" && export MANAGE_SBAND_COMM_NODE=0"
REMOTE_CMD+=" && export MANAGE_GROUND_TTC_GATEWAY=0"
REMOTE_CMD+=" && export CSP_TRANSPORT=$(printf '%q' "${CSP_TRANSPORT}")"
REMOTE_CMD+=" && export RUNTIME_ROOT=$(printf '%q' "${RUNTIME_ROOT}")"
REMOTE_CMD+=" && export PERSISTENT_ROOT=$(printf '%q' "${PERSISTENT_ROOT}")"
REMOTE_CMD+=" && export STAGING_ROOT=$(printf '%q' "${STAGING_ROOT}")"
REMOTE_CMD+=" && export LOG_ROOT=$(printf '%q' "${LOG_ROOT}")"
REMOTE_CMD+=" && export OBC_CLEANUP_RUNTIME_ROOT=$(printf '%q' "${RUNTIME_ROOT}")"
REMOTE_CMD+=" && exec $(printf '%q' "${REMOTE_RELEASE_ROOT}/launch/run_stack.sh")"

exec ssh "${OBC_SSH_TARGET}" "${REMOTE_CMD}"
